---
name: Desktop suites
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Suite_Name:
        type: choice
        description: 'Job to be run'
        required: true
        options:
          - FunctionalRegressionSuite
          - FunctionalSmokeSuite
          - testing

jobs:
  test:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.Suite_Name != ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: adopt

      - name: Installing porject dependencies and test
        run: | 
          mvn clean test -DSuite_Name=${{ github.event.inputs.Suite_Name }}
          
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Extend_report
          path: ./report
          retention-days: 5
