---
name: Mobile suites
on:
  push:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      Suite_Name:
        description: 'Job to be run'
        required: true
        default: 'FunctionalRegressionSuite'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: adopt

      - name: Installing porject dependencies
        run: | 
          mvn clean test -Dsuite=mobileSuites/${{ github.event.inputs.Suite_Name }}